environment: python
sdk:
  - hf_token: ${HF_TOKEN}
  - wandb_token: ${HF_TOKEN}
  - accelerate

build:
  system_packages:
    - libgl1-mesa-glx
    - libglib2.0-0
  python_packages:
    - unsloth>=2023.11.0
    - transformers>=4.34.0
    - torch>=2.0.0
    - accelerate>=0.23.0
    - bitsandbytes>=0.41.0
    - peft>=0.5.0
    - gradio>=3.40.0
    - pillow>=9.0.0
    - numpy>=1.22.0
    - trl>=0.7.4
    - datasets>=2.14.0
    - scikit-learn>=1.0.0
    - pandas>=2.0.0
    - matplotlib>=3.7.0
    - python-dotenv>=1.0.0
    - huggingface_hub>=0.17.0
    - tqdm>=4.65.0

metrics:
  - type: accuracy
    name: Accuracy
    description: Classification accuracy on validation set
  - type: loss
    name: Loss
    description: Training loss

widget:
  - title: Medical X-ray Analyzer
    description: Upload a chest X-ray image for analysis
    endpoint: 06_gradio_app.py:app
    metadata:
      - domain: medical
      - task: image-to-text
      - model: gemma-3-4b
      - dataset: nih-chest-xrays

dataset:
  path: nih-chest-xrays/nih-chest-xrays
  split: small
  revision: main

model:
  repo: unsloth/gemma-3-4b-it
  type: pretrained
  revision: main

compute:
  instance_type: gpu
  gpu: true
  cpu: 4
  memory: 16
